version: '3'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./.data:/home/dynamo/db
    environment:
      - JAVA_OPTS=-Djava.library.path=/home/dynamo/DynamoDBLocal_lib -Xmx512m -Xms256m
